name: fitai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Cliente HTTP / API (Resuelve DioException, FormData y MultipartFile) ---
  dio: ^5.4.0

  # --- Base de Datos Encriptada (Ambas declaradas para evitar el error de FileSystemException en Dart) ---
  sqlite3_flutter_libs: ^0.5.20
  sqlcipher_flutter_libs: ^0.6.0
  path_provider: ^2.1.0
  path: ^1.9.0
  flutter_secure_storage: ^9.2.0

  # --- Módulo 3: Cámara nativa en vivo ---
  camera: ^0.11.0

  # --- Módulo 3: Detección de pose anatómica LOCAL ---
  google_mlkit_pose_detection: ^0.13.0
  google_mlkit_commons: ^0.9.0

  # --- Módulo 5: Dictado por voz local ---
  speech_to_text: ^6.6.0

  # --- Módulo 5: Imágenes desde la API ---
  cached_network_image: ^3.3.0

  # --- Módulo 6: Notificaciones locales ---
  flutter_local_notifications: ^17.2.0

  # --- Estado global reactivo ---
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

